services:
  mongo1:
    image: mongo:7.0
    container_name: mongo1
    ports: ["27017:27017"]
    command: ["mongod", "--replSet=rs0", "--bind_ip_all"]
    volumes:
    - mongo1:/data/db      
    - ./data:/data         
  mongo2:
    image: mongo:7.0
    container_name: mongo2
    command: ["mongod", "--replSet=rs0", "--bind_ip_all"]
    volumes: ["mongo2:/data/db"]
  mongo3:
    image: mongo:7.0
    container_name: mongo3
    command: ["mongod", "--replSet=rs0", "--bind_ip_all"]
    volumes: ["mongo3:/data/db"]
volumes:
  mongo1:
  mongo2:
  mongo3:
